### ISSUE TITLE
node_modules inside repo

### ISSUE THREAD

**Issue by pdrazewski** [enetproduction/jedzonkoapp#1]
@KamilaBrylewska would you please be so kind as to remove node_modules from repository? thx

**Comment by KamilaBrylewska** [comment]
Bardzo chętnie tylko dodaj mnie do organizacji :)

**Comment by pdrazewski** [comment]
@KamilaBrylewska done.
switch to en lang please :)

**Comment by pdrazewski** [comment]
thx @KamilaBrylewska
